### ISSUE TITLE
Delphi Berlin doesn't work!

### ISSUE THREAD

**Issue by Valdeirsk8** [wendelb/DelphiOTP#1]
In Delphi Berlin this code isn't work, the generated code is diferent, I think the problem is the unicode, but I'm not sure, if you could to help me... thanks!

**Comment by wendelb** [comment]
I'm still stuck with XE2, so there is no chace for me to reproduce. As XE2 already uses WideString/Unicode as `string`, there should not be a unicode-problem.

Regarding your problem: "the generated code is diferent":
* Have you checked, that the time is synchronized across your devices?
* There is a Test Case in the Code: https://github.com/wendelb/DelphiOTP/blob/master/GoogleOTP.pas#L10 have you checked which parameter differ?
* If the test case works, there might be a timezone issue. In which one are you?

Please add a complete set of parameters (secret + counter) including the returned and the expected value of the function.

**Comment by Valdeirsk8** [comment]
I used the test Case and is working properly, sorry... but When I use the Google autenticator in the same device with the same pass code the result is different;

It is the test with Test Case!
![parameters](https://cloud.githubusercontent.com/assets/11742750/16766939/e7a120f8-480a-11e6-8855-f2f70f03278f.png)


Here there are two screenshot in the same device with the same Time zone, the first Image is the Google autenticator using this secret phrase plenussoftwareprivatekey based on time, the second is my app using the same secret phrase, but the result code is different
![screenshot_2016-07-12-08-32-02](https://cloud.githubusercontent.com/assets/11742750/16767344/ef9ae148-480c-11e6-80dc-fea654de0518.png)
![screenshot_2016-07-12-08-32-06](https://cloud.githubusercontent.com/assets/11742750/16767343/ef9a59da-480c-11e6-9847-486c2f52478f.png)

here is the version of the Google Autenticator
![screenshot_2016-07-12-08-33-04](https://cloud.githubusercontent.com/assets/11742750/16767345/ef9ef4fe-480c-11e6-8609-ffd52eeee170.png)

**Comment by Valdeirsk8** [comment]
Hello @wendelb were you right the problen is the timezone I change the function CodeUnixDateTime and its work.

thanks for helping me!!

It's necessary to declare `System.DateUtils` in uses;

`function CodeUnixDateTime(DatumZeit: TDateTime): Integer;
var
  wYear, wMonth, wDay, wHour, wMinute, wSecond, wMilliseconds: Word;
begin
  DecodeDateTime(DatumZeit, wYear, wMonth, wDay, wHour, wMinute, wSecond, wMilliseconds);
  Result := Round((EncodeDate(wYear, wMonth, wDay) - UnixDateDelta + EncodeTime(wHour, wMinute, wSecond, wMilliseconds)) * SecsPerDay);
end;
`

`if Counter <> -1 then
    Time := Counter
  else
    Time := CodeUnixDateTime(TTimeZone.Local.ToUniversalTime(Now)) div keyRegeneration;`

**Comment by wendelb** [comment]
Hey, thats great.

Do you want to create a pull request? - I'll be happy to merge.
