### ISSUE TITLE
git clone -bare issue

### ISSUE THREAD

**Issue by SkybuckFlying** [wendelb/DelphiOTP#11]
skybu@SuperPC2023 MINGW64 /k/Delphi/Libraries/DelphiOTP/git version/git bare repository
$ git clone -bare https://github.com/wendelb/DelphiOTP.git
Cloning into 'DelphiOTP'...
fatal: Remote branch are not found in upstream origin

WTF ?!?

**Comment by SkybuckFlying** [comment]
The only command that seems to work, thanks to copilot is:


```
skybu@SuperPC2023 MINGW64 /k/Delphi/Libraries/DelphiOTP/git version/git bare repository
$ git clone -b master https://github.com/wendelb/DelphiOTP.git "."
Cloning into '.'...
remote: Enumerating objects: 63, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 63 (delta 5), reused 7 (delta 3), pack-reused 47
Receiving objects: 100% (63/63), 97.58 KiB | 1.06 MiB/s, done.
Resolving deltas: 100% (24/24), done.
```

**Comment by SkybuckFlying** [comment]
Here is how I set it up, much more professional than I used to be, very nice, all versions directly accessable on harddisk but can still use gits functionalities to compare stuff.

(This integrates git's modus of operandus with skybuck's versioning method of using folders =D for now I high recommend it for software development of small projects, never loose code, always have access to any version immediately, not time wasted on previous builds if files are left intact (up to you).

Later:

```
skybu@SuperPC2023 MINGW64 /k/Delphi/Libraries/DelphiOTP/git version/git bare repository (master)
$ dir
Base32U.pas  Example  GoogleOTP.pas  LICENSE  README.md

skybu@SuperPC2023 MINGW64 /k/Delphi/Libraries/DelphiOTP/git version/git bare repository (master)
$ git branch original-version

skybu@SuperPC2023 MINGW64 /k/Delphi/Libraries/DelphiOTP/git version/git bare repository (master)
$ git branch version-1.00

skybu@SuperPC2023 MINGW64 /k/Delphi/Libraries/DelphiOTP/git version/git bare repository (master)
$ git branch version-1.01-test-on-delphi-12

skybu@SuperPC2023 MINGW64 /k/Delphi/Libraries/DelphiOTP/git version/git bare repository (master)
$ git worktree add "../original version" original-version
Preparing worktree (checking out 'original-version')
HEAD is now at 4335bda Merge pull request #10 from wendelb/license

skybu@SuperPC2023 MINGW64 /k/Delphi/Libraries/DelphiOTP/git version/git bare repository (master)
$ git worktree add "../version 1.00" version-1.00
Preparing worktree (checking out 'version-1.00')
HEAD is now at 4335bda Merge pull request #10 from wendelb/license

skybu@SuperPC2023 MINGW64 /k/Delphi/Libraries/DelphiOTP/git version/git bare repository (master)
$ git worktree add "../version 1.01 test on delphi 12" version-1.01-test-on-delphi-12
Preparing worktree (checking out 'version-1.01-test-on-delphi-12')
HEAD is now at 4335bda Merge pull request #10 from wendelb/license
```

**Comment by Iman-lmmv** [comment]
> skybu@SuperPC2023 MINGW64 /k/Delphi/Libraries/DelphiOTP/git version/git bare repository $ git clone -bare https://github.com/wendelb/DelphiOTP.git Cloning into 'DelphiOTP'... fatal: Remote branch are not found in upstream origin
> 
> WTF ?!?

We have the exact same issue !

**Comment by wendelb** [comment]
Guys, the first thing you should ask yourselves: Why would you want a bare repository? Pleas read up on what a bare repository is. 

> $ git clone -bare https://github.com/wendelb/DelphiOTP.git
This will clone the branch `are` that does not exist.

To get a bare repository, use `--bare`

**Comment by wendelb** [comment]
Closed, as this is not a git support channel
