### ISSUE TITLE
Issue with Git Cloning 

### ISSUE THREAD

**Issue by Iman-lmmv** [wendelb/DelphiOTP#14]

**Comment by wendelb** [comment]
You screenshot misses all of the stuff that is happening for this repository. Please show the lines preceding to the error message you marked. Copied text is usually better than a screenshot.

https://github.com/likeMindedLabs/Ltrx-ToolsAndDoc returns `Not found` for me. So I cannot look into that further.

**Comment by Iman-lmmv** [comment]
lmmv@Actarus:~$ git clone --recursive git@github.com:likeMindedLabs/Ltrx-ToolsAndDoc.git
Cloning into 'Ltrx-ToolsAndDoc'...
remote: Enumerating objects: 8855, done.
remote: Counting objects: 100% (851/851), done.
remote: Compressing objects: 100% (418/418), done.
remote: Total 8855 (delta 416), reused 718 (delta 400), pack-reused 8004
Receiving objects: 100% (8855/8855), 70.54 MiB | 66.27 MiB/s, done.
Resolving deltas: 100% (4646/4646), done.
Submodule 'docker' (git@github.com:likeMindedLabs/Ltrx-Docker.git) registered for path 'docker'
Submodule 'ltrx/trxengine' (git@github.com:likeMindedLabs/Ltrx-TrxEngine.git) registered for path 'ltrx/TrxEngine'
Submodule 'ltrx/core/VanBlackout' (git@github.com:likeMindedLabs/Ltrx-Core-VanBlackout.git) registered for path 'ltrx/core/VanBlackout'
Submodule 'ltrx/core/VanCommon' (git@github.com:likeMindedLabs/Ltrx-Core-VanCommon.git) registered for path 'ltrx/core/VanCommon'
Submodule 'ltrx/core/VanDrm' (git@github.com:likeMindedLabs/Ltrx-Core-VanDrm.git) registered for path 'ltrx/core/VanDrm'
Submodule 'ltrx/core/VanHttp' (git@github.com:likeMindedLabs/Ltrx-Core-VanHttp.git) registered for path 'ltrx/core/VanHttp'
Submodule 'ltrx/core/VanIcap' (git@github.com:likeMindedLabs/Ltrx-Core-VanIcap.git) registered for path 'ltrx/core/VanIcap'
Submodule 'ltrx/core/VanMms' (git@github.com:likeMindedLabs/Ltrx-Core-VanMms.git) registered for path 'ltrx/core/VanMms'
Submodule 'ltrx/core/VanPresentation' (git@github.com:likeMindedLabs/Ltrx-Core-VanPresentation.git) registered for path 'ltrx/core/VanPresentation'
Submodule 'ltrx/core/VanRtmp' (git@github.com:likeMindedLabs/Ltrx-Core-VanRtmp.git) registered for path 'ltrx/core/VanRtmp'
Submodule 'ltrx/core/VanRtsp' (git@github.com:likeMindedLabs/Ltrx-Core-VanRtsp.git) registered for path 'ltrx/core/VanRtsp'
Submodule 'ltrx/core/VanServerUtils' (git@github.com:likeMindedLabs/Ltrx-Core-VanServerUtils.git) registered for path 'ltrx/core/VanServerUtils'
Submodule 'ltrx/core/VanStats' (git@github.com:likeMindedLabs/Ltrx-Core-VanStats.git) registered for path 'ltrx/core/VanStats'
Submodule 'ltrx/core/VanTrxEngine' (git@github.com:likeMindedLabs/Ltrx-Core-VanTrxEngine.git) registered for path 'ltrx/core/VanTrxEngine'
Submodule 'ltrx/core/bmff' (git@github.com:likeMindedLabs/Ltrx-Core-bmff.git) registered for path 'ltrx/core/bmff'
Submodule 'ltrx/core/common' (git@github.com:likeMindedLabs/Ltrx-Core-common.git) registered for path 'ltrx/core/common'
Submodule 'ltrx/core/filters' (git@github.com:likeMindedLabs/Ltrx-Core-filters.git) registered for path 'ltrx/core/filters'
Submodule 'ltrx/core/lib/bitrate_adapt' (git@github.com:likeMindedLabs/Ltrx-Core-Lib-bitrate_adapt.git) registered for path 'ltrx/core/lib/bitrate_adapt'
Submodule 'ltrx/core/lib/cpu_cost_estimator' (git@github.com:likeMindedLabs/Ltrx-Core-Lib-cpu_cost_estimator.git) registered for path 'ltrx/core/lib/cpu_cost_estimator'
Submodule 'ltrx/core/lib/fileformat/3gpp' (git@github.com:likeMindedLabs/Ltrx-Core-Lib-FileFormat-3gpp.git) registered for path 'ltrx/core/lib/fileformat/3gpp'
Submodule 'ltrx/core/lib/fileformat/exr' (git@github.com:likeMindedLabs/Ltrx-Core-Lib-FileFormat-exr.git) registered for path 'ltrx/core/lib/fileformat/exr'
Submodule 'ltrx/core/lib/fileformat/flv' (git@github.com:likeMindedLabs/Ltrx-Core-Lib-FileFormat-flv.git) registered for path 'ltrx/core/lib/fileformat/flv'
Submodule 'ltrx/core/mediainfo' (git@github.com:likeMindedLabs/Ltrx-Core-mediainfo.git) registered for path 'ltrx/core/mediainfo'
Submodule 'ltrx/core/messaging' (git@github.com:likeMindedLabs/Ltrx-Core-messaging.git) registered for path 'ltrx/core/messaging'
Submodule 'ltrx/ext/codecs/BlackmagicRawAPI' (git@github.com:likeMindedLabs/Ltrx-Ext-Codecs-Blackmagic.git) registered for path 'ltrx/ext/codecs/BlackmagicRawAPI'
Submodule 'ltrx/ext/codecs/Ltrx-Ext-Codecs-Arri' (git@github.com:likeMindedLabs/Ltrx-Ext-Codecs-Arri.git) registered for path 'ltrx/ext/codecs/Ltrx-Ext-Codecs-Arri'
Submodule 'ltrx/ext/codecs/aacPlusV2dec' (git@github.com:likeMindedLabs/Ltrx-Ext-Codecs-aacPlusV2dec.git) registered for path 'ltrx/ext/codecs/aacPlusV2dec'
Submodule 'ltrx/ext/codecs/aacPlusV2enc' (git@github.com:likeMindedLabs/Ltrx-Ext-Codecs-aacPlusV2enc.git) registered for path 'ltrx/ext/codecs/aacPlusV2enc'
Submodule 'ltrx/ext/codecs/x264' (git@github.com:likeMindedLabs/Ltrx-Ext-Codecs-x264.git) registered for path 'ltrx/ext/codecs/x264'
Submodule 'ltrx/ext/ffmpeg' (git@github.com:likeMindedLabs/Ltrx-Ext-FFmpeg.git) registered for path 'ltrx/ext/ffmpeg'
Submodule 'ltrx/ext/filters/avid' (git@github.com:likeMindedLabs/Ltrx-Ext-Codecs-Avid.git) registered for path 'ltrx/ext/filters/avid'
Submodule 'ltrx/ext/gpu/gmmlib' (https://github.com/intel/gmmlib) registered for path 'ltrx/ext/gpu/gmmlib'
Submodule 'ltrx/ext/gpu/libva' (https://github.com/intel/libva) registered for path 'ltrx/ext/gpu/libva'
Submodule 'ltrx/ext/gpu/media-driver' (https://github.com/intel/media-driver) registered for path 'ltrx/ext/gpu/media-driver'
Submodule 'ltrx/ext/gst-build' (git@github.com:likeMindedLabs/Ltrx-Ext-gst-build.git) registered for path 'ltrx/ext/gst-build'
Submodule 'ltrx/ext/misc/aws' (git@github.com:likeMindedLabs/Ltrx-Ext-Misc-aws.git) registered for path 'ltrx/ext/misc/aws'
Submodule 'ltrx/ext/misc/firebase' (git@github.com:likeMindedLabs/Ltrx-Ext-Misc-firebase.git) registered for path 'ltrx/ext/misc/firebase'
Submodule 'ltrx/ext/misc/icu-release-66-1' (git@github.com:likeMindedLabs/icu-release-66-1.git) registered for path 'ltrx/ext/misc/icu-release-66-1'
Submodule 'ltrx/ext/misc/liboil' (git@github.com:likeMindedLabs/Ltrx-Ext-Misc-liboil.git) registered for path 'ltrx/ext/misc/liboil'
Submodule 'ltrx/ext/misc/log4cxx' (git@github.com:likeMindedLabs/Ltrx-Ext-Misc-log4cxx.git) registered for path 'ltrx/ext/misc/log4cxx'
Submodule 'ltrx/ext/misc/mongo-c-driver' (git@github.com:likeMindedLabs/Ltrx-Ext-Misc-mongo-c-driver.git) registered for path 'ltrx/ext/misc/mongo-c-driver'
Submodule 'ltrx/ext/misc/mongo-cxx-driver' (git@github.com:likeMindedLabs/Ltrx-Ext-Misc-mongo-cxx-driver.git) registered for path 'ltrx/ext/misc/mongo-cxx-driver'
Submodule 'ltrx/ext/misc/mosquitto' (git@github.com:eclipse/mosquitto.git) registered for path 'ltrx/ext/misc/mosquitto'
Submodule 'ltrx/ext/misc/ndi' (git@github.com:likeMindedLabs/Ltrx-Ext-Misc-ndi.git) registered for path 'ltrx/ext/misc/ndi'
Submodule 'ltrx/ext/misc/neon' (git@github.com:likeMindedLabs/Ltrx-Ext-Misc-neon.git) registered for path 'ltrx/ext/misc/neon'
Submodule 'ltrx/ext/misc/protobuf' (git@github.com:likeMindedLabs/Ltrx-Ext-Misc-protobuf.git) registered for path 'ltrx/ext/misc/protobuf'
Submodule 'ltrx/ext/misc/socket.io-client-cpp' (git@github.com:socketio/socket.io-client-cpp.git) registered for path 'ltrx/ext/misc/socket.io-client-cpp'
Submodule 'ltrx/ext/misc/websocketpp' (git@github.com:zaphoyd/websocketpp.git) registered for path 'ltrx/ext/misc/websocketpp'
Submodule 'ltrx/ext/misc/xml2' (git@github.com:likeMindedLabs/Ltrx-Ext-Misc-xml2.git) registered for path 'ltrx/ext/misc/xml2'
Submodule 'ltrx/ext/mux/libtsmux' (git@github.com:likeMindedLabs/Ltrx-Ext-Mux-libtsmux.git) registered for path 'ltrx/ext/mux/libtsmux'
Submodule 'ltrx/ext/src/cefsrc' (git@github.com:likeMindedLabs/Ltrx-Ext-Src-cefsrc.git) registered for path 'ltrx/ext/src/cefsrc'
Submodule 'tools/AudioPodsScript/LTRX_Toda_server/toda-audiopod-hub' (git@github.com:likeMindedLabs/toda-audiopod-hub.git) registered for path 'tools/AudioPodsScript/LTRX_Toda_server/toda-audiopod-hub'
Cloning into '/home/lmmv/Ltrx-ToolsAndDoc/docker'...
remote: Enumerating objects: 316, done.
remote: Counting objects: 100% (85/85), done.
remote: Compressing objects: 100% (74/74), done.
remote: Total 316 (delta 18), reused 25 (delta 11), pack-reused 231
Receiving objects: 100% (316/316), 57.99 KiB | 3.41 MiB/s, done.
Resolving deltas: 100% (159/159), done.
Cloning into '/home/lmmv/Ltrx-ToolsAndDoc/ltrx/TrxEngine'...
remote: Enumerating objects: 5911, done.
remote: Counting objects: 100% (2652/2652), done.
remote: Compressing objects: 100% (827/827), done.
remote: Total 5911 (delta 1933), reused 2121 (delta 1825), pack-reused 3259
Receiving objects: 100% (5911/5911), 2.18 MiB | 7.56 MiB/s, done.
Resolving deltas: 100% (4347/4347), done.
Cloning into '/home/lmmv/Ltrx-ToolsAndDoc/ltrx/core/VanBlackout'...
remote: Enumerating objects: 149, done.
remote: Counting objects: 100% (149/149), done.
remote: Compressing objects: 100% (95/95), done.
remote: Total 149 (delta 78), reused 120 (delta 52), pack-reused 0
Receiving objects: 100% (149/149), 38.81 KiB | 2.16 MiB/s, done.
Resolving deltas: 100% (78/78), done.
Cloning into '/home/lmmv/Ltrx-ToolsAndDoc/ltrx/core/VanCommon'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:likeMindedLabs/Ltrx-Core-VanCommon.git' into submodule path '/home/lmmv/Ltrx-ToolsAndDoc/ltrx/core/VanCommon' failed
Failed to clone 'ltrx/core/VanCommon'. Retry scheduled
Cloning into '/home/lmmv/Ltrx-ToolsAndDoc/ltrx/core/VanDrm'...
remote: Enumerating objects: 640, done.
remote: Counting objects: 100% (68/68), done.
remote: Compressing objects: 100% (61/61), done.
remote: Total 640 (delta 12), reused 15 (delta 7), pack-reused 572
Receiving objects: 100% (640/640), 196.41 KiB | 5.04 MiB/s, done.
Resolving deltas: 100% (420/420), done.
Cloning into '/home/lmmv/Ltrx-ToolsAndDoc/ltrx/core/VanHttp'...
remote: Enumerating objects: 118, done.
remote: Counting objects: 100% (118/118), done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 118 (delta 50), reused 102 (delta 36), pack-reused 0
Receiving objects: 100% (118/118), 42.53 KiB | 2.66 MiB/s, done.
Resolving deltas: 100% (50/50), done.
Cloning into '/home/lmmv/Ltrx-ToolsAndDoc/ltrx/core/VanIcap'...
remote: Enumerating objects: 105, done.
remote: Counting objects: 100% (105/105), done.
remote: Compressing objects: 100% (74/74), done.
remote: Total 105 (delta 40), reused 89 (delta 27), pack-reused 0
Receiving objects: 100% (105/105), 55.75 KiB | 2.14 MiB/s, done.
Resolving deltas: 100% (40/40), done.
Cloning into '/home/lmmv/Ltrx-ToolsAndDoc/ltrx/core/VanMms'...
remote: Enumerating objects: 149, done.
remote: Counting objects: 100% (149/149), done.
remote: Compressing objects: 100% (96/96), done.
remote: Total 149 (delta 63), reused 132 (delta 49), pack-reused 0
Receiving objects: 100% (149/149), 51.38 KiB | 2.33 MiB/s, done.
Resolving deltas: 100% (63/63), done.
Cloning into '/home/lmmv/Ltrx-ToolsAndDoc/ltrx/core/VanPresentation'...

**Comment by yves-lmmv** [comment]
BTW : It get stuck at different place if we redo it many time
