### ISSUE TITLE
Delphi Tokyo issues in Android

### ISSUE THREAD

**Issue by lainz** [wendelb/DelphiOTP#4]
Hi, I'm using a fork of this project (https://github.com/nikosdion/timecode) with Lazarus and now I'm using this project with Delphi Tokyo.

In both Lazarus and Delphi Tokyo for Win32 works really nice, I get the same tokens.

But for Android in Delphi Tokyo I get tokens that are not the same that the Delphi ones for Win32.

The code is really simple, is just using a string made with a secret part and an username.

Like:
`CalculateOTP('mysecret' + username);`

I've tried without using the username part and is the same.

My Android settings are:
- Android SDK 26
- Android NDK r15
- Java 1.8.0 131

**Comment by wendelb** [comment]
Thanks for bringing the fork to my attention. Didn't knew about it.

Regarding the tools you are using: I don't have access them, so I cannot locally reproduce.

Is your username base32 compliant? There should be neither a `1` nor a `0` in it.
CalculateOTP('mysecret' + username);

**Comment by lainz** [comment]
Thanks. That's the problem, I'm using a 0 on it. Maybe the same happens in the other bug.
