### ISSUE TITLE
Sometimes token generates 4 digits instead of 6

### ISSUE THREAD

**Issue by lainz** [wendelb/DelphiOTP#5]
I can't share my code since is propietary, but I can tell that sometimes with some strings I get a 4 digits code instead of 6.

The same code, first image 4 digits, second image 6 digits.
![errortoken](https://user-images.githubusercontent.com/4131395/37527594-2527392e-2911-11e8-8f8b-6de0d13bf248.PNG)
![good_token](https://user-images.githubusercontent.com/4131395/37527634-3e020190-2911-11e8-88c3-cd6b935f0030.PNG)

**Comment by wendelb** [comment]
This shouldn't happen at all. Since you cannot share the code, can you share the values that you inputted into the algorithm?

The code gives you the OTP as an `Integer`. How did you convert it into a string?

**Comment by lainz** [comment]
Hi, please send me an e-mail to ldiaz [at] arandusoft [dot] com, so I can send you the string and more details, because I can't share it to public.

**Comment by wendelb** [comment]
From what I can see, your token is `admin`, so the only other missing part is the counter value.

Have you tried using `Format('%.6d', [YourIntHere]);`?

**Comment by lainz** [comment]
Hi, for me the problem was the same as the other bug, that I used a non base64 string to feed the generator. Using a 0 inside it.

I will just change that and test.
