### ISSUE TITLE
This is not working with Google Auth and Microsoft Auth

### ISSUE THREAD

**Issue by paradey** [wendelb/DelphiOTP#7]
I tryed these codes but doesnt work. Validation is not succesfully with GAUTH.

**Comment by wendelb** [comment]
Thanks for opening that issue. Please add some details on what you actually did. Without those, nobody will be able to help you. The used algorithm was verified against the Google Authenticator App for Android. So it should be working.

**Comment by wendelb** [comment]
Closing, because there was no additional information. Please open a new one with some information. Thx.
