### ISSUE TITLE
deployment with other software?

### ISSUE THREAD

**Issue by marsupilami79** [wendelb/DelphiOTP#9]
Hello,

we plan to distribute DelphiOTP with a server component for Zeos (zeoslib.sourceforge.io). Is that allowed and if so under which license? Or is DelphiOTP considered to be public domain? Or should we send users here to get DelphiOTP themselves if they want to use OTPs?

Best regards,

Jan

**Comment by wendelb** [comment]
Hi Jan,

thanks for raising this issue. I thought, that I already added a Licence for this repository. Apparently I forgot to do that.
Going to fix that immediately.

I am going to add the MIT License to this code.

**Comment by wendelb** [comment]
Fixed. Please let me know if there are any more issues.

By the way, thanks for using this project. I'm glad it helps people.
